- package.json
> test: exports mocha bin

- bin/mocha.js
- package.json
https://github.com/eggjs/egg-bin/pull/13
> fix: link mocha bin from inner file

- lib/cov_command.js
- package.json
https://ci.appveyor.com/project/eggjs/egg/build/1.0.152/job/l6xnaa6an0nf3tus
不知道是否跟这个有关，先等一会看看。
> fix(cov): wait 1 second for Windows

- .autod.conf
- .travis.yml
- appveyor.yml
- lib/debug_command.js
- lib/start-cluster
- package.json
- test/egg-bin.test.js
- test/egg-debug.test.js
- test/egg-dev.test.js
closes https://github.com/eggjs/egg/issues/131
> feat: try to use --inspect first

- lib/helper.js
- lib/start-cluster
- test/egg-dev.test.js
pick https://github.com/eggjs/egg-bin/pull/27  https://github.com/eggjs/egg-bin/pull/28 to 1.x
> fix: should support -p

- test/egg-dev.test.js
> test: remove only

- lib/cmd/cov.js
- package.json
https://github.com/eggjs/egg/pull/605#issuecomment-287988440
> fix(cov): istanbul path env

- package.json
- test/egg-cov.test.js
> deps: upgrade istanbul to 1.1.0-alpha.1 (#43)

- README.md
- lib/cmd/cov.js
- test/fixtures/prerequire/test/index.test.js
- test/lib/cmd/cov.test.js
> feat(cov): add prerequire option

- lib/cmd/cov.js
- test/lib/cmd/cov.test.js
mocha will check arguments when there is no test files
> fix: don't pass prerequire

- lib/mocha-clean.js
> fix: clean more mocha error stack

- package.json
- test/lib/cmd/test.test.js
> test: skip assert error stack on node >= 7.0.0

- lib/cmd/cov.js
- test/lib/cmd/cov.test.js
close https://github.com/eggjs/egg/issues/1071
```bash
➜  egg-bin git:(master) n istanbul help report
Usage: istanbul report <options> [ <format> ... ]
```
> feat: cov support output json-summary

- lib/cmd/debug.js
- test/lib/cmd/debug.test.js
> chore: don't print DevTools link at vscode

- History.md
> chore: remove incorrect history

- test/lib/cmd/test.test.js
> test: Node 8.7.0 has improved stack for promise

- lib/cmd/test.js
> fix: make sure files sort in all platforms

- lib/cmd/cov.js
- test/fixtures/example-ts/package.json
- test/ts.test.js
> fix: remove ts extensions by default

- lib/command.js
- test/ts.test.js
> fix: support relative path

- lib/cmd/test.js
> fix: should ignore fixtures and node_modules

- package.json
> chore: update package.json for release

- README.md
- lib/cmd/dev.js
- test/lib/cmd/dev.test.js
close https://github.com/eggjs/egg/issues/3578
> fix: support --workers same as egg-scripts

- lib/command.js
- test/fixtures/my-egg-bin/lib/cmd/error.js
- test/my-egg-bin.test.js
override https://github.com/node-modules/common-bin/blob/master/lib/command.js#L144
> feat: should print error stack

- package.json
None.
- deps: remove semver from devDependencies
Remove duplicated `semver`:
https://github.com/eggjs/egg-bin/blob/9c99d3b3831af8280942f2063c036d5b6a111c7f/package.json#L29
https://github.com/eggjs/egg-bin/blob/9c99d3b3831af8280942f2063c036d5b6a111c7f/package.json#L53
- deps: fix high severity vulnerability by upgrade nyc
> deps: cleanup & fix high severity vulnerability

- test/fixtures/example-ts-cluster/node_modules/egg/index.js
- test/fixtures/example-ts-cluster/test/index.test.ts
- test/fixtures/example-ts-error-stack/node_modules/egg/index.js
- test/fixtures/example-ts-ets/node_modules/egg/index.js
- test/fixtures/example-ts-pkg/node_modules/egg/index.js
- test/fixtures/example-ts/node_modules/egg/index.js
- test/fixtures/example/node_modules/egg/index.js
- test/fixtures/ts/node_modules/aliyun-egg/index.js
- test/ts.test.js
1. 所有用例超时增加 1s
2. ts 测试用例超时再额外增加 3s
> ci: fix timeout

- package.json
> chore(deps): update typescript to ^3

- lib/cmd/dev.js
- package.json
- test/fixtures/my-egg-bin/lib/cmd/dev.js
- test/my-egg-bin.test.js
https://github.com/node-modules/common-bin/pull/42
> feat: expose proc

- History.md
- package.json
> Release 4.19.0

- lib/cmd/cov.js
- test/fixtures/bin/fake_mocha.js
- test/lib/cmd/cov.test.js
> fix: fix cov env

- lib/cmd/cov.js
> feat: default enable c8 report

- .github/workflows/nodejs.yml
- package.json
> 🤖 TEST: Only test on Linux and macOS

- lib/cmd/test.js
> fix: --full-trace should be boolean

- lib/cmd/test.js
> fix: add missing custom require

- lib/cmd/node-test.js
- lib/command.js
- lib/utils.js
- package.json
- test/fixtures/example-ts-ets/app/controller/home.ts
- test/fixtures/example-ts-ets/test/index.test.ts
- test/fixtures/example-ts-ets/tsconfig.json
- test/node-test-cov.test.js
- test/node-test.test.js
- test/ts.test.js
> feat: auto require tsconfig-paths/register on typescript command

- lib/cmd/test.js
- package.json
closes https://github.com/eggjs/egg/issues/5104
> feat: use mochawesome-with-mocha and enable mochawesome by default

- bin/postinstall.js
- package.json
closes https://github.com/eggjs/egg/issues/5116
> feat: auto run ets on postinstall

- bin/postinstall.js
> fix: should set ETS_CWD  to INIT_CWD on postinstall

- bin/postinstall.js
- lib/cmd/debug.js
- lib/cmd/dev.js
- package.json
- test/ets-bin.test.js
- test/fixtures/example-egg-module-ets/package.json
- test/lib/cmd/debug.test.js
- test/lib/cmd/test.test.js
> fix: ignore egg module on ets

- bin/postinstall.js
- test/ets-bin.test.js
- test/fixtures/example-egg-framework-ets/package.json
> fix: ignore postinstall run on egg framework

- lib/command.js
- test/lib/cmd/test.test.js
- test/ts.test.js
> fix: try to ready EGG_TYPESCRIPT env first

- bin/postinstall.js
This reverts commit fb3eb6aa8b0b3cd02eda28e0abce0e688bfdb4b4.
revert #214
> fix: not set ETS_FRAMEWORK

- bin/postinstall.js
deps on https://github.com/eggjs/egg-ts-helper/pull/104
> fix: set ETS_SCRIPT_FRAMEWORK

- src/bin/cli.ts
- src/cmd/test.ts
- test/cmd/cov.test.ts
- test/cmd/test.test.ts
- test/ts.test.ts
> feat: support grep pattern in 6.x

- .eslintignore
- package.json
- scripts/.eslintrc
- scripts/postinstall.js
- scripts/start-cluster.js
- src/bin/cli.ts
- src/cmd/dev.ts
- test/cmd/cov.test.ts
- test/cmd/debug.test.ts
- test/cmd/dev.test.ts
- test/cmd/test.test.ts
- test/ts.test.ts
closes https://github.com/eggjs/egg-bin/issues/218
> fix: add scripts dir to exclude

- .eslintrc
- package.json
- src/cmd/base.ts
- src/cmd/cov.ts
- src/cmd/dev.ts
- src/cmd/test.ts
- test/coffee.ts
- test/fixtures/example-ts-error-stack/test/index.test.ts
- test/fixtures/my-egg-bin/cmd/nsp.ts
- test/fixtures/my-egg-bin/config/framework.ts
- test/fixtures/ts/test/typescript.test.ts
- tsconfig.json
> feat: set target to ES2021

- package.json
- tsconfig.json
https://github.com/artus-cli/artus-cli/pull/37
> feat: tsc target to ES2022

- lib/cmd/cov.js
- lib/cmd/node-test-cov.js
- test/lib/cmd/cov-c8-report.test.js
- test/lib/cmd/cov.test.js
- test/node-test-cov.test.js
- test/ts.test.js
> feat: output cobertura report by default

- src/cmd/cov.ts
> feat: append cobertura to support diff line coverage

- package.json
Update egg-ts-helper 1.30.3 to 2.1.0
> feat: egg-ts-helper 1.30.3 to 2.1.0

- README.md
- test/lib/cmd/dal.test.js
> ci: fix await fs.stat

- lib/cmd/dal/gen.js
- lib/dal-gen.js
- package.json
> fix: move tegg to optional peer deps

- lib/cmd/dal/gen.js
- lib/dal-gen.js
- test/lib/cmd/dal.test.js
> feat: dal gen support pkg alias

- lib/cmd/dal/gen.js
> fix: fork dalgen with baseDir
